# Generated by Django 2.2.6 on 2019-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingpicture',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
