# Generated by Django 2.2.6 on 2019-10-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_picture', '0002_auto_20191030_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingpicture',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
