# Generated by Django 2.2.6 on 2019-10-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_picture', '0003_auto_20191030_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingpicture',
            name='picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
